url: ""
baseurl: ""
title: "The Creative Forum"
future: true

author:
  name: Yale Department of Spanish & Portuguese

collections:
  encounters:
    output: true
  projects:
    output: true

sass:
  load_paths:
    - _sass
