url: ""
baseurl: ""
title: "The Creative Forum"
future: true

owner: Yale Department of Spanish & Portuguese
email: creativeforum@yale.edu

collections:
  encounters:
    output: true
  projects:
    output: true
  special:
    output: true

sass:
  load_paths:
    - _sass
