url: "" 
baseurl: "" 
title: "The Creative Forum" 
subtitle: "Yale Department of Spanish & Portuguese"

author:
    name: Yale Department of Spanish & Portuguese

sass:
    load_paths: 
        - _sass